// DO NOT EDIT — generated by scripts/gen_element_catalog.py.
//
// Astrid's element registry and renderers remain authoritative. This file is
// the deterministic, data-only projection imported by editor hosts such as
// Reigh; regenerate it when an element manifest or component changes.

export const ASTRID_ELEMENT_CATALOG_VERSION = 1 as const;

export type AstridRenderingElementKind = 'effect' | 'animation' | 'transition';

export type AstridRenderingElementParameter = {
  name: string;
  label: string;
  description: string;
  type: 'number' | 'select' | 'boolean' | 'color' | 'audio-binding';
  default?: number | string | boolean;
  min?: number;
  max?: number;
  step?: number;
  options?: {label: string; value: string}[];
};

export type AstridRenderingElementDescriptor = {
  id: string;
  kind: AstridRenderingElementKind;
  label: string;
  description: string;
  shortDescription: string;
  keywords: string[];
  defaults: Record<string, unknown>;
  schema: Record<string, unknown>;
  parameters: AstridRenderingElementParameter[];
  source: string;
  packId: string;
  componentPath: string;
  revision: string;
  runtime: Record<string, unknown>;
  renderability: {
    preview: 'supported' | 'blocked' | 'unknown';
    browserExport: 'supported' | 'blocked' | 'unknown';
    workerExport: 'supported' | 'blocked' | 'unknown';
  };
};

export const ASTRID_ELEMENT_CATALOG: readonly AstridRenderingElementDescriptor[] = Object.freeze(
[
  {
    "componentPath": "packs/rendering/elements/animations/fade/component.tsx",
    "defaults": {
      "durationFrames": 12
    },
    "description": "Fade animation wrapper for entrance/exit phases over a configurable duration.",
    "id": "fade",
    "keywords": [
      "fade",
      "animation",
      "wrapper",
      "entrance",
      "exit"
    ],
    "kind": "animation",
    "label": "Fade",
    "packId": "rendering",
    "parameters": [
      {
        "default": 12,
        "description": "",
        "label": "Duration Frames",
        "min": 1,
        "name": "durationFrames",
        "type": "number"
      }
    ],
    "renderability": {
      "browserExport": "supported",
      "preview": "supported",
      "workerExport": "supported"
    },
    "revision": "sha256:4e2ec24b03dd3876df06427705d78470a9ddb74656ba264027dcb1df84f57c58",
    "runtime": {
      "adapter": "remotion"
    },
    "schema": {
      "properties": {
        "durationFrames": {
          "minimum": 1,
          "type": "number"
        }
      },
      "type": "object"
    },
    "shortDescription": "Fade in/out wrapper animation.",
    "source": "pack:rendering"
  },
  {
    "componentPath": "packs/rendering/elements/animations/fade-up/component.tsx",
    "defaults": {
      "durationFrames": 18
    },
    "description": "Fade-up entrance animation (combined fade and upward motion).",
    "id": "fade-up",
    "keywords": [
      "fade",
      "up",
      "animation",
      "entrance",
      "motion"
    ],
    "kind": "animation",
    "label": "Fade Up",
    "packId": "rendering",
    "parameters": [
      {
        "default": 18,
        "description": "",
        "label": "Duration Frames",
        "min": 1,
        "name": "durationFrames",
        "type": "number"
      }
    ],
    "renderability": {
      "browserExport": "supported",
      "preview": "supported",
      "workerExport": "supported"
    },
    "revision": "sha256:099f3fc94833353d2efd1c4b36d8b80c5a2752372597e30fcc4751711482768e",
    "runtime": {
      "adapter": "remotion"
    },
    "schema": {
      "properties": {
        "durationFrames": {
          "minimum": 1,
          "type": "number"
        }
      },
      "type": "object"
    },
    "shortDescription": "Fade up entrance animation.",
    "source": "pack:rendering"
  },
  {
    "componentPath": "packs/rendering/elements/animations/scale-in/component.tsx",
    "defaults": {
      "durationFrames": 18
    },
    "description": "Scale-in entrance animation that grows the element to full size.",
    "id": "scale-in",
    "keywords": [
      "scale",
      "animation",
      "entrance",
      "grow",
      "motion"
    ],
    "kind": "animation",
    "label": "Scale In",
    "packId": "rendering",
    "parameters": [
      {
        "default": 18,
        "description": "",
        "label": "Duration Frames",
        "min": 1,
        "name": "durationFrames",
        "type": "number"
      }
    ],
    "renderability": {
      "browserExport": "supported",
      "preview": "supported",
      "workerExport": "supported"
    },
    "revision": "sha256:080a88d13277c0916d7ce31c5e386d4d2b58827a2cf33febcb337ea83465649c",
    "runtime": {
      "adapter": "remotion"
    },
    "schema": {
      "properties": {
        "durationFrames": {
          "minimum": 1,
          "type": "number"
        }
      },
      "type": "object"
    },
    "shortDescription": "Scale in entrance animation.",
    "source": "pack:rendering"
  },
  {
    "componentPath": "packs/rendering/elements/animations/slide-left/component.tsx",
    "defaults": {
      "durationFrames": 18
    },
    "description": "Slide-left entrance animation that translates the element in from the right.",
    "id": "slide-left",
    "keywords": [
      "slide",
      "left",
      "animation",
      "entrance",
      "motion"
    ],
    "kind": "animation",
    "label": "Slide Left",
    "packId": "rendering",
    "parameters": [
      {
        "default": 18,
        "description": "",
        "label": "Duration Frames",
        "min": 1,
        "name": "durationFrames",
        "type": "number"
      }
    ],
    "renderability": {
      "browserExport": "supported",
      "preview": "supported",
      "workerExport": "supported"
    },
    "revision": "sha256:fe6e126904f16a02d38df9a87d0b344a74c69aa398747740440c5c5d15897d20",
    "runtime": {
      "adapter": "remotion"
    },
    "schema": {
      "properties": {
        "durationFrames": {
          "minimum": 1,
          "type": "number"
        }
      },
      "type": "object"
    },
    "shortDescription": "Slide left entrance animation.",
    "source": "pack:rendering"
  },
  {
    "componentPath": "packs/rendering/elements/animations/slide-up/component.tsx",
    "defaults": {
      "durationFrames": 12
    },
    "description": "Slide-up exit animation that translates the element upward off-screen.",
    "id": "slide-up",
    "keywords": [
      "slide",
      "up",
      "animation",
      "exit",
      "motion"
    ],
    "kind": "animation",
    "label": "Slide Up",
    "packId": "rendering",
    "parameters": [
      {
        "default": 12,
        "description": "",
        "label": "Duration Frames",
        "min": 1,
        "name": "durationFrames",
        "type": "number"
      }
    ],
    "renderability": {
      "browserExport": "supported",
      "preview": "supported",
      "workerExport": "supported"
    },
    "revision": "sha256:3da761065dc77ebd05f6e4fbf980181d9b37394d4d3980be546ba45471eb5433",
    "runtime": {
      "adapter": "remotion"
    },
    "schema": {
      "properties": {
        "durationFrames": {
          "minimum": 1,
          "type": "number"
        }
      },
      "type": "object"
    },
    "shortDescription": "Slide up exit animation.",
    "source": "pack:rendering"
  },
  {
    "componentPath": "packs/rendering/elements/animations/type-on/component.tsx",
    "defaults": {
      "durationFraction": 0.55,
      "durationFrames": 120,
      "showCaret": true,
      "startFrame": 18
    },
    "description": "Type-on text animation that reveals characters sequentially.",
    "id": "type-on",
    "keywords": [
      "type",
      "typewriter",
      "text",
      "animation",
      "entrance",
      "reveal"
    ],
    "kind": "animation",
    "label": "Type On",
    "packId": "rendering",
    "parameters": [
      {
        "default": 120,
        "description": "",
        "label": "Duration Frames",
        "min": 1,
        "name": "durationFrames",
        "type": "number"
      }
    ],
    "renderability": {
      "browserExport": "supported",
      "preview": "supported",
      "workerExport": "supported"
    },
    "revision": "sha256:a172cb3e67560604f014ec114d50da08fd4979d36119adb94b6a9ba7c3bd420c",
    "runtime": {
      "adapter": "remotion"
    },
    "schema": {
      "properties": {
        "durationFrames": {
          "minimum": 1,
          "type": "number"
        }
      },
      "type": "object"
    },
    "shortDescription": "Typewriter-style text reveal animation.",
    "source": "pack:rendering"
  },
  {
    "componentPath": "packs/local/elements/effects/animated-media-transform/component.tsx",
    "defaults": {
      "fit": "contain",
      "keyframes": [
        {
          "at": 0,
          "height": 1080,
          "opacity": 1,
          "width": 1920,
          "x": 0,
          "y": 0
        }
      ]
    },
    "description": "Clip-local transform keyframes interpolate in authored canvas pixels. Optional source playback segments independently preserve trims, speed changes and deliberate source resets inside one timeline clip. Uses the same component in live preview and Remotion rendering.",
    "id": "animated-media-transform",
    "keywords": [
      "media",
      "video",
      "image",
      "zoom",
      "pan",
      "fade",
      "keyframes"
    ],
    "kind": "effect",
    "label": "Animated Media Transform",
    "packId": "local",
    "parameters": [
      {
        "default": "contain",
        "description": "",
        "label": "Fit",
        "name": "fit",
        "options": [
          {
            "label": "Contain",
            "value": "contain"
          },
          {
            "label": "Cover",
            "value": "cover"
          },
          {
            "label": "Fill",
            "value": "fill"
          }
        ],
        "type": "select"
      }
    ],
    "renderability": {
      "browserExport": "unknown",
      "preview": "unknown",
      "workerExport": "unknown"
    },
    "revision": "sha256:1a77ddcc6debb85f665e3655d4a23aaad8e57d57540754d6883ca4b04aa32f39",
    "runtime": {},
    "schema": {
      "additionalProperties": false,
      "properties": {
        "fit": {
          "enum": [
            "contain",
            "cover",
            "fill"
          ],
          "type": "string"
        },
        "keyframes": {
          "description": "Increasing clip-local seconds with x/y/width/height in canvas pixels. Values interpolate linearly and clamp outside the range.",
          "items": {
            "additionalProperties": false,
            "properties": {
              "at": {
                "minimum": 0,
                "type": "number"
              },
              "height": {
                "exclusiveMinimum": 0,
                "type": "number"
              },
              "opacity": {
                "maximum": 1,
                "minimum": 0,
                "type": "number"
              },
              "width": {
                "exclusiveMinimum": 0,
                "type": "number"
              },
              "x": {
                "type": "number"
              },
              "y": {
                "type": "number"
              }
            },
            "required": [
              "at",
              "x",
              "y",
              "width",
              "height",
              "opacity"
            ],
            "type": "object"
          },
          "minItems": 1,
          "type": "array"
        },
        "sourceSegments": {
          "description": "Video playback sections starting at clip-local seconds; first at 0. Rounded frame boundaries must be distinct.",
          "items": {
            "additionalProperties": false,
            "properties": {
              "at": {
                "minimum": 0,
                "type": "number"
              },
              "sourceStart": {
                "minimum": 0,
                "type": "number"
              },
              "speed": {
                "exclusiveMinimum": 0,
                "type": "number"
              }
            },
            "required": [
              "at",
              "sourceStart",
              "speed"
            ],
            "type": "object"
          },
          "minItems": 1,
          "type": "array"
        }
      },
      "required": [
        "keyframes"
      ],
      "type": "object"
    },
    "shortDescription": "Animate one managed image or video through editable position, size and opacity keyframes.",
    "source": "pack:local"
  },
  {
    "componentPath": "packs/rendering/elements/effects/audio-reactive-colour/component.tsx",
    "defaults": {
      "events": [],
      "initialColor": "#000000",
      "schemaVersion": 1
    },
    "description": "A deterministic full-frame colour effect driven by approved clip-relative frame events. Rendering can specialize this exact contract to FFmpeg without changing timeline semantics.",
    "id": "audio-reactive-colour",
    "keywords": [
      "audio-reactive",
      "colour",
      "markers",
      "beats",
      "timeline",
      "ffmpeg"
    ],
    "kind": "effect",
    "label": "Audio-reactive colour",
    "packId": "rendering",
    "parameters": [
      {
        "default": "#000000",
        "description": "",
        "label": "Initial Color",
        "name": "initialColor",
        "type": "color"
      },
      {
        "default": 1,
        "description": "",
        "label": "Schema Version",
        "name": "schemaVersion",
        "type": "number"
      }
    ],
    "renderability": {
      "browserExport": "supported",
      "preview": "supported",
      "workerExport": "supported"
    },
    "revision": "sha256:b05ba83a03c60c94acfbde56d04b8b46d76b4e7c6982612c5c9b7a5e9ccd23f1",
    "runtime": {
      "adapter": "remotion"
    },
    "schema": {
      "additionalProperties": false,
      "properties": {
        "events": {
          "items": {
            "additionalProperties": false,
            "properties": {
              "color": {
                "pattern": "^#[0-9A-Fa-f]{6}$",
                "type": "string"
              },
              "frame": {
                "minimum": 1,
                "type": "integer"
              },
              "id": {
                "minLength": 1,
                "type": "string"
              }
            },
            "required": [
              "frame",
              "color"
            ],
            "type": "object"
          },
          "type": "array"
        },
        "initialColor": {
          "pattern": "^#[0-9A-Fa-f]{6}$",
          "type": "string"
        },
        "schemaVersion": {
          "enum": [
            1
          ],
          "type": "integer"
        }
      },
      "required": [
        "initialColor",
        "events"
      ],
      "type": "object"
    },
    "shortDescription": "Fill the frame with colours selected by frozen integer-frame markers.",
    "source": "pack:rendering"
  },
  {
    "componentPath": "packs/local/elements/effects/end-codex-transform/component.tsx",
    "defaults": {
      "duration": 6.383
    },
    "description": "Renders the base shot plate, then three reference cards above beam into a timeline row below; targets flash, glow amber, and swap into new images. Duration-relative phases.",
    "id": "end-codex-transform",
    "keywords": [
      "transform",
      "timeline",
      "insert",
      "astrid-intro"
    ],
    "kind": "effect",
    "label": "Ending Codex Transform",
    "packId": "local",
    "parameters": [],
    "renderability": {
      "browserExport": "unknown",
      "preview": "unknown",
      "workerExport": "unknown"
    },
    "revision": "sha256:b9158b705cc0f0799561832a87c52b2136af7904227e41c42e2ef2d4de0456ff",
    "runtime": {},
    "schema": {
      "additionalProperties": true,
      "properties": {},
      "type": "object"
    },
    "shortDescription": "Reference images connect into timeline images and transform them.",
    "source": "pack:local"
  },
  {
    "componentPath": "packs/local/elements/effects/end-mid-combined/component.tsx",
    "defaults": {
      "duration": 14.464
    },
    "description": "Renders the base plate, draws each beat's caption in turn, plays references plugging into a persistent timeline row, then two images lifting out with loading videos. Duration-relative phases; replaces shots 16 and 17 with a single unbroken shot.",
    "id": "end-mid-combined",
    "keywords": [
      "transform",
      "animate",
      "insert",
      "astrid-intro"
    ],
    "kind": "effect",
    "label": "Ending Combined Insert",
    "packId": "local",
    "parameters": [],
    "renderability": {
      "browserExport": "unknown",
      "preview": "unknown",
      "workerExport": "unknown"
    },
    "revision": "sha256:31bc798b142d8bd9029d49f5d4f33479813394ec37873c8d081571f9d3930b0e",
    "runtime": {},
    "schema": {
      "additionalProperties": true,
      "properties": {},
      "type": "object"
    },
    "shortDescription": "One continuous codex-then-minimax insert over a single plate.",
    "source": "pack:local"
  },
  {
    "componentPath": "packs/local/elements/effects/end-minimax-animate/component.tsx",
    "defaults": {
      "duration": 8.081
    },
    "description": "Renders the base shot plate, then a timeline row appears; two images lift out below, each connected to a loading-then-playing video card above. Duration-relative phases.",
    "id": "end-minimax-animate",
    "keywords": [
      "animate",
      "timeline",
      "insert",
      "astrid-intro"
    ],
    "kind": "effect",
    "label": "Ending Minimax Animate",
    "packId": "local",
    "parameters": [],
    "renderability": {
      "browserExport": "unknown",
      "preview": "unknown",
      "workerExport": "unknown"
    },
    "revision": "sha256:52fc67d8ce10a3b9a17027532836909cd23f2721dda9fd0c0fba02617e9d7d88",
    "runtime": {},
    "schema": {
      "additionalProperties": true,
      "properties": {},
      "type": "object"
    },
    "shortDescription": "Timeline images lift out below while their videos load and play above.",
    "source": "pack:local"
  },
  {
    "componentPath": "packs/local/elements/effects/end-spanning-layer/component.tsx",
    "defaults": {},
    "description": "Transparent Remotion overlay for the ending workflow. The clip-local sequence adapts to caller supplied phase durations for material preparation, PowerPoint words and timing, separate anchor/keyframe references, and a live workflow review. It reorders the supplied timeline cards, highlights the selected segment, and plays the managed source video for that segment. Phase timing and timeline data are supplied through clip params so narration revisions do not require a component change.",
    "id": "end-spanning-layer",
    "keywords": [
      "timeline",
      "overlay",
      "insert",
      "astrid-intro"
    ],
    "kind": "effect",
    "label": "Ending Spanning Layer",
    "packId": "local",
    "parameters": [
      {
        "description": "",
        "label": "Anchors Seconds",
        "name": "anchorsSeconds",
        "type": "number"
      },
      {
        "description": "",
        "label": "Iteration Seconds",
        "name": "iterationSeconds",
        "type": "number"
      },
      {
        "description": "",
        "label": "Prep Seconds",
        "name": "prepSeconds",
        "type": "number"
      },
      {
        "description": "",
        "label": "Prep Source End",
        "name": "prepSourceEnd",
        "type": "number"
      },
      {
        "description": "",
        "label": "Prep Source Speed",
        "name": "prepSourceSpeed",
        "type": "number"
      },
      {
        "description": "",
        "label": "Prep Source Start",
        "min": 0,
        "name": "prepSourceStart",
        "type": "number"
      },
      {
        "description": "",
        "label": "Selected Segment Index",
        "min": 0,
        "name": "selectedSegmentIndex",
        "type": "number"
      },
      {
        "description": "",
        "label": "Workflow Seconds",
        "name": "workflowSeconds",
        "type": "number"
      }
    ],
    "renderability": {
      "browserExport": "unknown",
      "preview": "unknown",
      "workerExport": "unknown"
    },
    "revision": "sha256:414fdb61e457bf2710008986740dfc692468782b57d01b3830c70e48322fa29c",
    "runtime": {},
    "schema": {
      "additionalProperties": true,
      "properties": {
        "anchorsSeconds": {
          "exclusiveMinimum": 0,
          "type": "number"
        },
        "headings": {
          "description": "Optional short headings for the four visual phases.",
          "properties": {
            "anchors": {
              "type": "string"
            },
            "iteration": {
              "type": "string"
            },
            "prep": {
              "type": "string"
            },
            "workflow": {
              "type": "string"
            }
          },
          "type": "object"
        },
        "iterationSeconds": {
          "exclusiveMinimum": 0,
          "type": "number"
        },
        "phaseDurations": {
          "description": "Positive clip-local seconds for prep, iteration, anchors, and workflow.",
          "properties": {
            "anchors": {
              "exclusiveMinimum": 0,
              "type": "number"
            },
            "iteration": {
              "exclusiveMinimum": 0,
              "type": "number"
            },
            "prep": {
              "exclusiveMinimum": 0,
              "type": "number"
            },
            "workflow": {
              "exclusiveMinimum": 0,
              "type": "number"
            }
          },
          "type": "object"
        },
        "prepSeconds": {
          "exclusiveMinimum": 0,
          "type": "number"
        },
        "prepSourceEnd": {
          "exclusiveMinimum": 0,
          "type": "number"
        },
        "prepSourceSpeed": {
          "exclusiveMinimum": 0,
          "type": "number"
        },
        "prepSourceStart": {
          "minimum": 0,
          "type": "number"
        },
        "selectedSegmentId": {
          "type": "string"
        },
        "selectedSegmentIndex": {
          "minimum": 0,
          "type": "integer"
        },
        "timelineSegments": {
          "description": "Ordered source timeline sections; start and end are seconds in the managed source video.",
          "items": {
            "properties": {
              "end": {
                "exclusiveMinimum": 0,
                "type": "number"
              },
              "id": {
                "type": "string"
              },
              "label": {
                "type": "string"
              },
              "sourceEnd": {
                "exclusiveMinimum": 0,
                "type": "number"
              },
              "sourceStart": {
                "minimum": 0,
                "type": "number"
              },
              "speed": {
                "exclusiveMinimum": 0,
                "type": "number"
              },
              "start": {
                "minimum": 0,
                "type": "number"
              },
              "title": {
                "type": "string"
              }
            },
            "required": [
              "start",
              "end",
              "label",
              "title"
            ],
            "type": "object"
          },
          "type": "array"
        },
        "workflowSeconds": {
          "exclusiveMinimum": 0,
          "type": "number"
        }
      },
      "type": "object"
    },
    "shortDescription": "Flexible amber workflow timeline with real moving output and keyframe references.",
    "source": "pack:local"
  },
  {
    "componentPath": "packs/local/elements/effects/ending-carousel/component.tsx",
    "defaults": {
      "duration": 9.193
    },
    "description": "Renders the base shot plate full-screen, then plays a four-phase carousel over the middle band (fly-through, pick with amber glow, lay onto an amber timeline track, zoom out). Phase timing is relative to clip duration. Cards and plate resolve through params.__astridAssets.",
    "id": "ending-carousel",
    "keywords": [
      "carousel",
      "timeline",
      "insert",
      "astrid-intro"
    ],
    "kind": "effect",
    "label": "Ending Carousel",
    "packId": "local",
    "parameters": [],
    "renderability": {
      "browserExport": "unknown",
      "preview": "unknown",
      "workerExport": "unknown"
    },
    "revision": "sha256:f250e02ea437f7698b23dc495071a45a7716aeb6b97282c12c8e9fae3f7efa6a",
    "runtime": {},
    "schema": {
      "additionalProperties": true,
      "properties": {},
      "type": "object"
    },
    "shortDescription": "Image carousel insert that flies cards through, picks one, and lays them onto a timeline.",
    "source": "pack:local"
  },
  {
    "componentPath": "packs/local/elements/effects/event-card/component.tsx",
    "defaults": {
      "content": "Event Card",
      "height": 520,
      "postProcess": "glow",
      "subtitle": "DOM layout captured into canvas.",
      "width": 900
    },
    "description": "Event Card uses Remotion HtmlInCanvas to capture DOM content and post-process it as a canvas texture.",
    "id": "event-card",
    "keywords": [
      "html",
      "canvas",
      "remotion",
      "effect",
      "card"
    ],
    "kind": "effect",
    "label": "Event Card",
    "packId": "local",
    "parameters": [
      {
        "default": 520,
        "description": "",
        "label": "Height",
        "name": "height",
        "type": "number"
      },
      {
        "default": "glow",
        "description": "",
        "label": "Post Process",
        "name": "postProcess",
        "options": [
          {
            "label": "None",
            "value": "none"
          },
          {
            "label": "Soft Blur",
            "value": "soft-blur"
          },
          {
            "label": "Glow",
            "value": "glow"
          },
          {
            "label": "Vignette",
            "value": "vignette"
          }
        ],
        "type": "select"
      },
      {
        "default": 900,
        "description": "",
        "label": "Width",
        "name": "width",
        "type": "number"
      }
    ],
    "renderability": {
      "browserExport": "unknown",
      "preview": "unknown",
      "workerExport": "unknown"
    },
    "revision": "sha256:980d5df6673695c5eced22ce6054372465f6d46b856b062b03ea1438e082399d",
    "runtime": {},
    "schema": {
      "properties": {
        "accent": {
          "type": "string"
        },
        "background": {
          "type": "string"
        },
        "content": {
          "type": "string"
        },
        "foreground": {
          "type": "string"
        },
        "height": {
          "type": "number"
        },
        "postProcess": {
          "enum": [
            "none",
            "soft-blur",
            "glow",
            "vignette"
          ],
          "type": "string"
        },
        "subtitle": {
          "type": "string"
        },
        "width": {
          "type": "number"
        }
      },
      "type": "object"
    },
    "shortDescription": "DOM-to-canvas Remotion effect for post-processed cards.",
    "source": "pack:local"
  },
  {
    "componentPath": "packs/local/elements/effects/frame-overlay/component.tsx",
    "defaults": {
      "duration": 115.699
    },
    "description": "Renders the canonical tight-frame borderless overlay fullscreen over everything below. One clip spans the whole timeline on the top frame track; hold must equal total duration and is recomputed whenever VO retimes.",
    "id": "frame-overlay",
    "keywords": [
      "frame",
      "border",
      "overlay",
      "astrid-intro"
    ],
    "kind": "effect",
    "label": "Frame Overlay",
    "packId": "local",
    "parameters": [],
    "renderability": {
      "browserExport": "unknown",
      "preview": "unknown",
      "workerExport": "unknown"
    },
    "revision": "sha256:e22e45f1c65f92721cfc3b9d84ed2a137b50e9b2e3552ae9c176aa385ab9fb18",
    "runtime": {},
    "schema": {
      "additionalProperties": true,
      "properties": {},
      "type": "object"
    },
    "shortDescription": "Full-frame tight amber border overlay.",
    "source": "pack:local"
  },
  {
    "componentPath": "packs/local/elements/effects/model-trends/component.tsx",
    "defaults": {
      "accent": "#9F1C1C",
      "anchor": "top-right",
      "background": "rgba(8, 8, 14, 0.86)",
      "borderRadius": "14px",
      "height": 420,
      "offsetX": 60,
      "offsetY": 60,
      "padding": "20px",
      "width": 540
    },
    "description": "Local-pack ModelTrends overlay for /1m-style 'Models Come and Go' visualization. Renders a stacked-area chart (sd, animatediff, flux, wan, cogvideo, hunyuan, ltx) plus a cumulative-messages counter. Animation is driven entirely by useCurrentFrame() — Remotion controls timing, no DOM animation hooks. Chart and dataset are baked-in (sample WRAPPED_DATA from constants.ts). Sized for a corner overlay on a 1920x1080 video.",
    "id": "model-trends",
    "keywords": [
      "chart",
      "trends",
      "stacked-area",
      "wrapped",
      "models",
      "overlay"
    ],
    "kind": "effect",
    "label": "Model Trends Chart",
    "packId": "local",
    "parameters": [
      {
        "default": "top-right",
        "description": "",
        "label": "Anchor",
        "name": "anchor",
        "options": [
          {
            "label": "Top Left",
            "value": "top-left"
          },
          {
            "label": "Top",
            "value": "top"
          },
          {
            "label": "Top Right",
            "value": "top-right"
          },
          {
            "label": "Left",
            "value": "left"
          },
          {
            "label": "Center",
            "value": "center"
          },
          {
            "label": "Right",
            "value": "right"
          },
          {
            "label": "Bottom Left",
            "value": "bottom-left"
          },
          {
            "label": "Bottom",
            "value": "bottom"
          },
          {
            "label": "Bottom Right",
            "value": "bottom-right"
          }
        ],
        "type": "select"
      },
      {
        "default": 420,
        "description": "",
        "label": "Height",
        "name": "height",
        "type": "number"
      },
      {
        "default": 60,
        "description": "",
        "label": "Offset X",
        "name": "offsetX",
        "type": "number"
      },
      {
        "default": 60,
        "description": "",
        "label": "Offset Y",
        "name": "offsetY",
        "type": "number"
      },
      {
        "default": 540,
        "description": "",
        "label": "Width",
        "name": "width",
        "type": "number"
      }
    ],
    "renderability": {
      "browserExport": "unknown",
      "preview": "unknown",
      "workerExport": "unknown"
    },
    "revision": "sha256:0b8e68d6613333e55c8f000f471335a385d66e30d26bef8bbf4f9a31f1be5c67",
    "runtime": {},
    "schema": {
      "additionalProperties": true,
      "properties": {
        "accent": {
          "type": "string"
        },
        "anchor": {
          "enum": [
            "top-left",
            "top",
            "top-right",
            "left",
            "center",
            "right",
            "bottom-left",
            "bottom",
            "bottom-right"
          ],
          "type": "string"
        },
        "backdropFilter": {
          "type": "string"
        },
        "background": {
          "type": "string"
        },
        "border": {
          "type": "string"
        },
        "borderRadius": {
          "type": [
            "number",
            "string"
          ]
        },
        "boxShadow": {
          "type": "string"
        },
        "height": {
          "type": "number"
        },
        "offsetX": {
          "type": "number"
        },
        "offsetY": {
          "type": "number"
        },
        "padding": {
          "type": [
            "number",
            "string"
          ]
        },
        "width": {
          "type": "number"
        }
      },
      "type": "object"
    },
    "shortDescription": "Animated stacked-area chart of model-family share-of-conversation, driven by Remotion frame.",
    "source": "pack:local"
  },
  {
    "componentPath": "packs/local/elements/effects/neon-orbit-card/component.tsx",
    "defaults": {
      "content": "Neon Orbit",
      "height": 520,
      "postProcess": "glow",
      "subtitle": "DOM layout captured into canvas.",
      "width": 900
    },
    "description": "A luminous HTML-in-canvas title card for testing canvas post-processing.",
    "id": "neon-orbit-card",
    "keywords": [
      "html",
      "canvas",
      "remotion",
      "effect",
      "card"
    ],
    "kind": "effect",
    "label": "Neon Orbit",
    "packId": "local",
    "parameters": [
      {
        "default": 520,
        "description": "",
        "label": "Height",
        "name": "height",
        "type": "number"
      },
      {
        "default": "glow",
        "description": "",
        "label": "Post Process",
        "name": "postProcess",
        "options": [
          {
            "label": "None",
            "value": "none"
          },
          {
            "label": "Soft Blur",
            "value": "soft-blur"
          },
          {
            "label": "Glow",
            "value": "glow"
          },
          {
            "label": "Vignette",
            "value": "vignette"
          }
        ],
        "type": "select"
      },
      {
        "default": 900,
        "description": "",
        "label": "Width",
        "name": "width",
        "type": "number"
      }
    ],
    "renderability": {
      "browserExport": "unknown",
      "preview": "unknown",
      "workerExport": "unknown"
    },
    "revision": "sha256:371aa948d5ea501781a64fe1b9ab3a907f214db2420158be6cb2dad4d19c0d82",
    "runtime": {},
    "schema": {
      "properties": {
        "accent": {
          "type": "string"
        },
        "background": {
          "type": "string"
        },
        "content": {
          "type": "string"
        },
        "foreground": {
          "type": "string"
        },
        "height": {
          "type": "number"
        },
        "postProcess": {
          "enum": [
            "none",
            "soft-blur",
            "glow",
            "vignette"
          ],
          "type": "string"
        },
        "subtitle": {
          "type": "string"
        },
        "width": {
          "type": "number"
        }
      },
      "type": "object"
    },
    "shortDescription": "DOM-to-canvas Remotion effect for post-processed cards.",
    "source": "pack:local"
  },
  {
    "componentPath": "packs/local/elements/effects/scrolling-guide/component.tsx",
    "defaults": {
      "heading": "MAKING VIDEOS",
      "scrollEnd": 440,
      "scrollStart": 0,
      "side": "right",
      "subheading": "A SMALL GUIDE TO THE REVIEW LOOP"
    },
    "description": "A reusable Remotion overlay that keeps the authored composition centered and scrolls concise Astrid workflow guidance inside a right-hand document panel. The left side remains transparent for a separate character or source clip.",
    "id": "scrolling-guide",
    "keywords": [
      "guide",
      "scroll",
      "workflow",
      "review",
      "document",
      "overlay"
    ],
    "kind": "effect",
    "label": "Scrolling Video Guide",
    "packId": "local",
    "parameters": [
      {
        "default": 440,
        "description": "",
        "label": "Scroll End",
        "min": 0,
        "name": "scrollEnd",
        "type": "number"
      },
      {
        "default": 0,
        "description": "",
        "label": "Scroll Start",
        "min": 0,
        "name": "scrollStart",
        "type": "number"
      },
      {
        "default": "right",
        "description": "",
        "label": "Side",
        "name": "side",
        "options": [
          {
            "label": "Left",
            "value": "left"
          },
          {
            "label": "Right",
            "value": "right"
          }
        ],
        "type": "select"
      }
    ],
    "renderability": {
      "browserExport": "unknown",
      "preview": "unknown",
      "workerExport": "unknown"
    },
    "revision": "sha256:b40b6b45ed2586a47cb0814cdcd0e75d6013e79562af4dabfc17645700ca3369",
    "runtime": {},
    "schema": {
      "additionalProperties": true,
      "properties": {
        "heading": {
          "type": "string"
        },
        "scrollEnd": {
          "minimum": 0,
          "type": "number"
        },
        "scrollStart": {
          "minimum": 0,
          "type": "number"
        },
        "sections": {
          "items": {
            "additionalProperties": false,
            "properties": {
              "heading": {
                "type": "string"
              },
              "lines": {
                "items": {
                  "type": "string"
                },
                "type": "array"
              },
              "number": {
                "type": "string"
              }
            },
            "required": [
              "number",
              "heading",
              "lines"
            ],
            "type": "object"
          },
          "type": "array"
        },
        "side": {
          "enum": [
            "left",
            "right"
          ],
          "type": "string"
        },
        "subheading": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "shortDescription": "Transparent orange and cream scrolling guide for the video-making workflow.",
    "source": "pack:local"
  },
  {
    "componentPath": "packs/local/elements/effects/sliding-media/component.tsx",
    "defaults": {
      "duration": 2
    },
    "description": "Renders a video or image asset full-screen and applies clip-level fade/slide effects (fade_in, fade_out, slide_in_x, slide_out_x).",
    "id": "sliding-media",
    "keywords": [
      "media",
      "slide",
      "transition"
    ],
    "kind": "effect",
    "label": "Sliding Media",
    "packId": "local",
    "parameters": [
      {
        "description": "",
        "label": "Object Fit",
        "name": "objectFit",
        "options": [
          {
            "label": "Cover",
            "value": "cover"
          },
          {
            "label": "Contain",
            "value": "contain"
          }
        ],
        "type": "select"
      }
    ],
    "renderability": {
      "browserExport": "unknown",
      "preview": "unknown",
      "workerExport": "unknown"
    },
    "revision": "sha256:c20c84d94202f45e81e3439ab4b57cd163120c140e2373c379c3e3be9cba49e2",
    "runtime": {},
    "schema": {
      "additionalProperties": true,
      "properties": {
        "objectFit": {
          "enum": [
            "cover",
            "contain"
          ],
          "type": "string"
        }
      },
      "type": "object"
    },
    "shortDescription": "Full-screen media clip with slide-in/out motion.",
    "source": "pack:local"
  },
  {
    "componentPath": "packs/rendering/elements/effects/text-card/component.tsx",
    "defaults": {
      "align": "center",
      "content": ""
    },
    "description": "Default rendered text card effect for simple captions and titles.",
    "id": "text-card",
    "keywords": [
      "text",
      "card",
      "effect",
      "caption",
      "title"
    ],
    "kind": "effect",
    "label": "Text Card",
    "packId": "rendering",
    "parameters": [
      {
        "default": "center",
        "description": "",
        "label": "Align",
        "name": "align",
        "options": [
          {
            "label": "Left",
            "value": "left"
          },
          {
            "label": "Center",
            "value": "center"
          },
          {
            "label": "Right",
            "value": "right"
          }
        ],
        "type": "select"
      }
    ],
    "renderability": {
      "browserExport": "supported",
      "preview": "supported",
      "workerExport": "supported"
    },
    "revision": "sha256:be91276caabc6b8d87eb9174e073128a26d593a0cd042abc08225b1b224e2173",
    "runtime": {
      "adapter": "remotion"
    },
    "schema": {
      "properties": {
        "align": {
          "enum": [
            "left",
            "center",
            "right"
          ],
          "type": "string"
        },
        "content": {
          "type": "string"
        }
      },
      "required": [
        "content"
      ],
      "type": "object"
    },
    "shortDescription": "Default text card effect for captions and titles.",
    "source": "pack:rendering"
  },
  {
    "componentPath": "packs/local/elements/effects/vibe-comfy-asset-overlay/component.tsx",
    "defaults": {
      "duration": 10
    },
    "description": "Transparent Remotion overlay that animates existing Vibe Comfy PNG microassets, independent platform/title assets, and a procedural noodle path over a media background.",
    "id": "vibe-comfy-asset-overlay",
    "keywords": [
      "remotion",
      "bumper",
      "assets",
      "noodle",
      "vibe-comfy"
    ],
    "kind": "effect",
    "label": "Vibe Comfy Asset Overlay",
    "packId": "local",
    "parameters": [],
    "renderability": {
      "browserExport": "unknown",
      "preview": "unknown",
      "workerExport": "unknown"
    },
    "revision": "sha256:49faeec4044b643a523e48f6817b70846108ee3249386ba63a9b9097b1239d77",
    "runtime": {},
    "schema": {
      "additionalProperties": true,
      "properties": {
        "accent": {
          "type": "string"
        },
        "green": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "shortDescription": "Asset-driven Vibe Comfy overlay with procedural noodle.",
    "source": "pack:local"
  },
  {
    "componentPath": "packs/local/elements/effects/vibe-comfy-bumper/component.tsx",
    "defaults": {
      "duration": 10,
      "title": "VIBE COMFY"
    },
    "description": "Frame-driven Vibe Comfy bumper with a procedural SVG noodle path, platform, title, and animated micro-assets.",
    "id": "vibe-comfy-bumper",
    "keywords": [
      "remotion",
      "bumper",
      "noodle",
      "ui",
      "vibe-comfy"
    ],
    "kind": "effect",
    "label": "Vibe Comfy Bumper",
    "packId": "local",
    "parameters": [],
    "renderability": {
      "browserExport": "unknown",
      "preview": "unknown",
      "workerExport": "unknown"
    },
    "revision": "sha256:284904a96c699898b2ffa272b08068bb8d9d0edb75163d3f0d781b04614067b6",
    "runtime": {},
    "schema": {
      "additionalProperties": true,
      "properties": {
        "accent": {
          "type": "string"
        },
        "background": {
          "type": "string"
        },
        "green": {
          "type": "string"
        },
        "title": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "shortDescription": "Procedural Remotion bumper for Vibe Comfy.",
    "source": "pack:local"
  },
  {
    "componentPath": "packs/rendering/elements/transitions/cross-fade/component.tsx",
    "defaults": {
      "durationFrames": 8
    },
    "description": "Cross-fade transition that blends out one clip while blending in the next.",
    "id": "cross-fade",
    "keywords": [
      "cross-fade",
      "transition",
      "blend",
      "fade"
    ],
    "kind": "transition",
    "label": "Cross Fade",
    "packId": "rendering",
    "parameters": [
      {
        "default": 8,
        "description": "",
        "label": "Duration Frames",
        "min": 1,
        "name": "durationFrames",
        "type": "number"
      }
    ],
    "renderability": {
      "browserExport": "supported",
      "preview": "supported",
      "workerExport": "supported"
    },
    "revision": "sha256:4a778cae5c12cadc88d08f3907f34b3312cff97c3acaae884fc095db88c0bd82",
    "runtime": {
      "adapter": "remotion"
    },
    "schema": {
      "properties": {
        "durationFrames": {
          "minimum": 1,
          "type": "number"
        }
      },
      "type": "object"
    },
    "shortDescription": "Cross fade transition.",
    "source": "pack:rendering"
  },
  {
    "componentPath": "packs/rendering/elements/transitions/fade/component.tsx",
    "defaults": {
      "durationFrames": 8
    },
    "description": "Fade transition through black between two clips.",
    "id": "fade",
    "keywords": [
      "fade",
      "transition",
      "black"
    ],
    "kind": "transition",
    "label": "Fade",
    "packId": "rendering",
    "parameters": [
      {
        "default": 8,
        "description": "",
        "label": "Duration Frames",
        "min": 1,
        "name": "durationFrames",
        "type": "number"
      }
    ],
    "renderability": {
      "browserExport": "supported",
      "preview": "supported",
      "workerExport": "supported"
    },
    "revision": "sha256:2826b5183c88f6161b7f59a4ab686637ad29eff5f86f843968b6850c977d204a",
    "runtime": {
      "adapter": "remotion"
    },
    "schema": {
      "properties": {
        "durationFrames": {
          "minimum": 1,
          "type": "number"
        }
      },
      "type": "object"
    },
    "shortDescription": "Fade-through-black transition.",
    "source": "pack:rendering"
  }
]
);

// Backwards-compatible name used by the editor integration.
export const ASTRID_RENDERING_ELEMENTS = ASTRID_ELEMENT_CATALOG;

export const ASTRID_EFFECT_CATALOG = ASTRID_ELEMENT_CATALOG.filter((element) => element.kind === 'effect');
export const ASTRID_ANIMATION_CATALOG = ASTRID_ELEMENT_CATALOG.filter((element) => element.kind === 'animation');
export const ASTRID_TRANSITION_CATALOG = ASTRID_ELEMENT_CATALOG.filter((element) => element.kind === 'transition');
