// DO NOT EDIT — generated by scripts/gen_editor_extension_catalog.py.
//
// Pack manifests remain authoritative. This build-time projection imports only
// declared browser entries and is consumed by Reigh's trusted extension loader.

import type { ReighExtension } from '@reigh/editor-sdk';
import editorExtension0 from './live-scenes/extension';

export type AstridEditorExtensionDescriptor = {
  readonly packId: string;
  readonly entryPath: string;
  readonly extension: ReighExtension;
};

export const ASTRID_EDITOR_EXTENSION_CATALOG: readonly AstridEditorExtensionDescriptor[] = Object.freeze([
  { packId: 'rendering', entryPath: 'editor/live-scenes/extension.tsx', extension: editorExtension0 },
]);

export const ASTRID_EDITOR_EXTENSIONS: readonly ReighExtension[] = Object.freeze(
  ASTRID_EDITOR_EXTENSION_CATALOG.map(({ extension }) => extension),
);
