"""Generated, product-neutral client for the workspace.v1 protocol."""

from .generated import (
    ApiError,
    AttemptFence,
    ClaimWaiting,
    ByteResponse,
    Capability,
    Event,
    Executor,
    Generation,
    GenerationVariant,
    Health,
    IntegrityCheck,
    IntegrityReport,
    Handshake,
    ManagedObject,
    ManagedOutput,
    ObjectLocation,
    ShotTextBinding,
    MutationResult,
    Project,
    ProjectDocument,
    PreferenceResource,
    PreferenceMutationResult,
    Realm,
    RealmLifecycle,
    RecoveryAuthorization,
    RecoveryCheckpointReceipt,
    RecoveryReceipt,
    RecoveryResumeReceipt,
    Task,
    WorkspaceClient,
)

__all__ = ["ApiError", "AttemptFence", "ClaimWaiting", "ByteResponse", "Capability", "Event", "Executor", "Generation", "GenerationVariant", "Handshake", "Health", "IntegrityCheck", "IntegrityReport", "ManagedObject", "ManagedOutput", "ObjectLocation", "ShotTextBinding", "MutationResult", "Project", "ProjectDocument", "PreferenceResource", "PreferenceMutationResult", "Realm", "RealmLifecycle", "RecoveryAuthorization", "RecoveryCheckpointReceipt", "RecoveryReceipt", "RecoveryResumeReceipt", "Task", "WorkspaceClient"]
