#!/usr/bin/env python3
"""Generate Remotion TypeScript types from banodoco_schema.py."""

# The repository root is inserted before importing Astrid so this script works
# directly from a checkout; that intentional path bootstrap triggers E402.
# ruff: noqa: E402

import argparse
import sys
import types
from pathlib import Path
from typing import Any, Literal, NotRequired, Required, Union, get_args, get_origin, get_type_hints
from typing import is_typeddict as _stdlib_is_typeddict

from typing_extensions import is_typeddict as _ext_is_typeddict


def is_typeddict(value: object) -> bool:
    return _stdlib_is_typeddict(value) or _ext_is_typeddict(value)


REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

import astrid.core.timeline as timeline

BANNER = "\n".join(
    [
        "// DO NOT EDIT — generated by tools/scripts/gen_remotion_types.py",
        "//",
        "// Naming convention: TypedDicts re-exported from",
        "// banodoco_timeline_schema (AssetEntry, Theme, ThemeOverrides,",
        "// TimelineClip, TimelineConfig, TimelineOutput) are emitted with the",
        "// `Shared*` name as the canonical TS interface. The un-prefixed name",
        "// (plus any other in-repo alias such as AssetRegistryEntry) is emitted",
        "// as `export type X = SharedX;` for back-compat. New code should",
        "// prefer the `Shared*` name.",
    ]
)
DEFAULT_OUTPUT = REPO_ROOT / "remotion" / "src" / "types.generated.ts"
ARRAY_NAMES = [
    "_ASSET_ENTRY_ALLOWED",
    "_CLIP_ALLOWED",
    "_THEME_OVERRIDES_ALLOWED",
    "_TIMELINE_TOP_ALLOWED",
    "_TRACK_ALLOWED",
]

# Per-(canonical_interface_name, field_name) overrides.
#
# Used where the upstream Pydantic class is byte-distinct from the astrid-local
# TS companion type (e.g. upstream `Track` vs astrid-local `TrackDefinition`),
# or where the astrid-side validator has a wider view than the upstream JSON
# Schema (e.g. AnimationReferenceList accepts string|object|list while upstream
# Entrance/Exit/Continuous is the object branch only).
_FIELD_TYPE_OVERRIDES: dict[tuple[str, str], str] = {
    ("SharedTimelineClip", "text"): "TextClipData",
    ("SharedTimelineClip", "entrance"): "AnimationReferenceList",
    ("SharedTimelineClip", "exit"): "AnimationReferenceList",
    ("SharedTimelineClip", "continuous"): "AnimationReferenceList",
    ("SharedTimelineClip", "transition"): "ClipTransitionReference | string",
    ("SharedTimelineClip", "effects"): "TimelineEffect[] | Record<string, number>",
    ("SharedTimelineConfig", "clips"): "SharedTimelineClip[]",
    ("SharedTimelineConfig", "tracks"): "TrackDefinition[]",
    ("SharedTimelineConfig", "output"): "SharedTimelineOutput",
    ("SharedTimelineConfig", "pinnedShotGroups"): "Record<string, unknown>[]",
    ("SharedTimelineConfig", "theme_overrides"): "SharedThemeOverrides",
}


def _is_public_typeddict(name: str, value: object) -> bool:
    return not name.startswith("_") and is_typeddict(value)


def _build_typeddict_registry() -> tuple[
    dict[int, str], list[tuple[str, type[Any]]], dict[int, list[str]]
]:
    """Group TypedDicts by class identity and pick the canonical emit name.

    Returns ``(canonical_by_id, ordered_canonical_emissions, aliases_by_id)``.
    Canonical is the ``Shared*``-prefixed alias when present (matches the
    Pydantic import-as direction in ``astrid/core/timeline/banodoco_schema.py``); otherwise
    the alphabetically-first alias. Every other name pointing at the same
    class becomes a ``export type X = Canonical;`` back-compat alias.
    """
    members = [
        (name, value) for name, value in vars(timeline).items() if _is_public_typeddict(name, value)
    ]
    by_id: dict[int, list[str]] = {}
    value_by_id: dict[int, type[Any]] = {}
    for name, value in members:
        by_id.setdefault(id(value), []).append(name)
        value_by_id[id(value)] = value

    # Exported TypedDicts can refer to private implementation-detail
    # TypedDicts (for example SharedAssetEntry -> DerivedFrom).  Walk those
    # annotations so every name emitted in a field type also gets an interface.
    queue = list(value_by_id.values())
    visited: set[int] = set()
    while queue:
        typed_dict = queue.pop()
        if id(typed_dict) in visited:
            continue
        visited.add(id(typed_dict))
        names = by_id[id(typed_dict)]
        shared = sorted(name for name in names if name.startswith("Shared"))
        canonical_name = shared[0] if shared else sorted(names)[0]
        for field_name, annotation in get_type_hints(typed_dict, include_extras=True).items():
            # An override replaces the complete upstream annotation at the TS
            # boundary. Do not recursively emit private codegen types that are
            # reachable only through that replaced annotation: shared schema
            # releases can expose a private ``Clip`` behind
            # SharedTimelineConfig.clips, which otherwise collides with the
            # intentional public ``Clip = SharedTimelineClip`` compatibility
            # alias below.
            if (canonical_name, field_name) in _FIELD_TYPE_OVERRIDES:
                continue
            pending = [annotation]
            while pending:
                candidate = pending.pop()
                origin = get_origin(candidate)
                if isinstance(candidate, type) and is_typeddict(candidate):
                    if id(candidate) not in value_by_id:
                        value_by_id[id(candidate)] = candidate
                        by_id[id(candidate)] = [candidate.__name__]
                        queue.append(candidate)
                    continue
                if origin is not None:
                    pending.extend(get_args(candidate))

    canonical_by_id: dict[int, str] = {}
    aliases_by_id: dict[int, list[str]] = {}
    for type_id, names in by_id.items():
        shared = sorted(name for name in names if name.startswith("Shared"))
        canonical = shared[0] if shared else sorted(names)[0]
        canonical_by_id[type_id] = canonical
        aliases_by_id[type_id] = sorted(name for name in names if name != canonical)

    ordered = sorted(
        ((canonical_by_id[type_id], value_by_id[type_id]) for type_id in by_id),
        key=lambda item: item[0],
    )
    return canonical_by_id, ordered, aliases_by_id


_CANONICAL_BY_ID, _ORDERED_CANONICAL, _ALIASES_BY_ID = _build_typeddict_registry()


def _field_name(interface_name: str, field_name: str) -> str:
    if interface_name in {"TimelineClip", "SharedTimelineClip"} and field_name == "from_":
        return "from"
    return field_name


def _unwrap_not_required(annotation: Any) -> tuple[Any, bool]:
    """Strip a single ``NotRequired``/``Required`` wrapper.

    Returns ``(inner_annotation, is_optional_marker)``. TypedDicts produced by
    upstream Pydantic schemas use ``total=True`` with per-field ``NotRequired``
    markers, so ``__required_keys__`` reports every key as required and the
    per-field marker is the only reliable optionality signal.
    """
    origin = get_origin(annotation)
    if origin is NotRequired:
        (inner,) = get_args(annotation)
        return inner, True
    if origin is Required:
        (inner,) = get_args(annotation)
        return inner, False
    return annotation, False


def _render_literal(args: tuple[Any, ...]) -> str:
    parts = [repr(value) if not isinstance(value, str) else f"'{value}'" for value in args]
    return " | ".join(sorted(parts))


def _render_union(args: tuple[Any, ...]) -> str:
    rendered = sorted({_render_type(arg) for arg in args})
    return " | ".join(rendered)


def _render_type(annotation: Any) -> str:
    annotation, _ = _unwrap_not_required(annotation)
    origin = get_origin(annotation)
    if annotation is Any:
        return "unknown"
    if annotation is str:
        return "string"
    if annotation in (int, float):
        return "number"
    if annotation is bool:
        return "boolean"
    if annotation is type(None):
        return "null"
    if origin is Literal:
        return _render_literal(get_args(annotation))
    if origin in (list, list[Any]):
        (item_type,) = get_args(annotation)
        return f"{_render_type(item_type)}[]"
    if origin in (dict, dict[Any, Any]):
        key_type, value_type = get_args(annotation)
        key = "string" if key_type is str else _render_type(key_type)
        value = _render_type(value_type)
        return f"Record<{key}, {value}>"
    if origin in (Union, types.UnionType):
        return _render_union(get_args(annotation))
    if isinstance(annotation, type) and is_typeddict(annotation):
        canonical = _CANONICAL_BY_ID.get(id(annotation))
        return canonical if canonical else annotation.__name__
    if isinstance(annotation, type):
        return annotation.__name__
    return "unknown"


def _render_interface(name: str, typed_dict: type[Any]) -> str:
    hints = get_type_hints(typed_dict, include_extras=True)
    required_keys = set(typed_dict.__required_keys__)
    field_names = sorted(hints)
    lines = [f"export interface {name} {{"]
    for field_name in field_names:
        rendered_name = _field_name(name, field_name)
        annotation = hints[field_name]
        unwrapped, optional_marker = _unwrap_not_required(annotation)
        is_required = (field_name in required_keys) and not optional_marker
        optional = "" if is_required else "?"
        override = _FIELD_TYPE_OVERRIDES.get((name, field_name))
        rendered_type = override if override is not None else _render_type(unwrapped)
        lines.append(f"  {rendered_name}{optional}: {rendered_type};")
    lines.append("}")
    return "\n".join(lines)


def _render_allowed_arrays() -> list[str]:
    rendered = []
    for name in ARRAY_NAMES:
        values = sorted(getattr(timeline, name))
        joined = ", ".join(f"'{value}'" for value in values)
        rendered.append(f"export const {name} = [{joined}] as const;")
    return rendered


def _render_animation_reference_list_alias() -> str:
    return (
        "export type AnimationReferenceList =\n"
        "  | string\n"
        "  | AnimationReferenceObject\n"
        "  | (string | AnimationReferenceObject)[];"
    )


def generate() -> str:
    canonical_names = {name for name, _typed_dict in _ORDERED_CANONICAL}
    blocks = [BANNER, "", _render_animation_reference_list_alias()]
    for canonical_name, typed_dict in _ORDERED_CANONICAL:
        blocks.append("")
        blocks.append(_render_interface(canonical_name, typed_dict))
        for alias_name in _ALIASES_BY_ID.get(id(typed_dict), []):
            blocks.append("")
            blocks.append(f"export type {alias_name} = {canonical_name};")
        if canonical_name == "SharedTimelineClip":
            aliases = _ALIASES_BY_ID.get(id(typed_dict), [])
            # The legacy ``Clip`` name is only ours to alias when nothing
            # else emitted it: with the shared schema package installed the
            # annotation walk discovers the upstream ``Clip`` TypedDict and
            # emits its interface, so a second ``Clip`` binding here would
            # be a TS2300 duplicate identifier.
            if "Clip" not in aliases and "Clip" not in canonical_names:
                blocks.append("")
                blocks.append("export type Clip = SharedTimelineClip;")
    blocks.append("")
    blocks.extend(_render_allowed_arrays())
    blocks.append("")
    return "\n".join(blocks)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("output", nargs="?", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument(
        "--include-element-registries",
        action="store_true",
        help="also refresh the element registries under the same outer lock",
    )
    return parser


def _main_unlocked(argv: list[str] | None = None) -> int:
    """Write generated artifacts while the caller owns the Remotion lock."""

    args = build_parser().parse_args(argv)
    output_path = args.output.resolve()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(generate(), encoding="utf-8")
    if args.include_element_registries:
        from scripts import gen_effect_registry

        return gen_effect_registry._main_unlocked([])
    return 0


def main(argv: list[str] | None = None) -> int:
    from astrid.packs.rendering.rendering.renderers.remotion import lock as remotion_lock

    if remotion_lock.remotion_render_lock_held():
        return _main_unlocked(argv)
    with remotion_lock.remotion_render_lock():
        return _main_unlocked(argv)


if __name__ == "__main__":
    raise SystemExit(main())
