#!/usr/bin/env python3
"""Generate the build-time browser extension projection for editor hosts."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from astrid.core.pack import (  # noqa: E402
    discover_packs,
    pack_editor_entry_paths,
)

DEFAULT_OUTPUT = REPO_ROOT / "astrid" / "packs" / "rendering" / "editor" / "catalog.ts"

BANNER = """// DO NOT EDIT — generated by scripts/gen_editor_extension_catalog.py.
//
// Pack manifests remain authoritative. This build-time projection imports only
// declared browser entries and is consumed by Reigh's trusted extension loader.
"""
def _module_spec(pack_root: Path, entry: Path, output: Path, pack_id: str) -> str:
    module_path = entry.with_suffix("")
    if pack_root == output.parent.parent.resolve():
        relative = module_path.relative_to(pack_root / "editor").as_posix()
        return f"./{relative}"
    return f"@astrid/packs/{pack_id}/{module_path.relative_to(pack_root).as_posix()}"


def generate(output: Path = DEFAULT_OUTPUT) -> str:
    rows: list[tuple[str, str, Path, str]] = []
    for pack in discover_packs():
        for entry in pack_editor_entry_paths(pack):
            entry_path = entry.relative_to(pack.root).as_posix()
            rows.append(
                (
                    pack.id,
                    entry_path,
                    entry,
                    _module_spec(pack.root, entry, output.resolve(), pack.id),
                )
            )
    rows.sort(key=lambda row: (row[0], row[1]))

    imports = [
        f"import editorExtension{index} from {module_spec!r};"
        for index, (_, _, _, module_spec) in enumerate(rows)
    ]
    descriptors = [
        "  {"
        f" packId: {pack_id!r},"
        f" entryPath: {entry_path!r},"
        f" extension: editorExtension{index}"
        " }"
        for index, (pack_id, entry_path, _, _) in enumerate(rows)
    ]

    return "\n".join(
        (
            BANNER.rstrip(),
            "",
            "import type { ReighExtension } from '@reigh/editor-sdk';",
            *imports,
            "",
            "export type AstridEditorExtensionDescriptor = {",
            "  readonly packId: string;",
            "  readonly entryPath: string;",
            "  readonly extension: ReighExtension;",
            "};",
            "",
            "export const ASTRID_EDITOR_EXTENSION_CATALOG: readonly AstridEditorExtensionDescriptor[] = Object.freeze([",
            *[f"{descriptor}," for descriptor in descriptors],
            "]);",
            "",
            "export const ASTRID_EDITOR_EXTENSIONS: readonly ReighExtension[] = Object.freeze(",
            "  ASTRID_EDITOR_EXTENSION_CATALOG.map(({ extension }) => extension),",
            ");",
            "",
        )
    )


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("output", nargs="?", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when the checked-in projection differs from generated output",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    output = args.output.resolve()
    expected = generate(output)
    actual = output.read_text(encoding="utf-8") if output.is_file() else None
    if args.check:
        if actual != expected:
            print(f"{output} is stale; run scripts/gen_editor_extension_catalog.py", file=sys.stderr)
            return 1
        return 0
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
