#!/usr/bin/env python3
"""Generate the editor-facing Astrid element catalog projection."""

from __future__ import annotations

import argparse
import json
import logging
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from astrid.core.element.catalog import (  # noqa: E402
    EDITOR_CATALOG_VERSION,
    _clear_registry_cache,
    list_element_descriptors,
)

DEFAULT_OUTPUT = REPO_ROOT / "astrid" / "packs" / "rendering" / "elements" / "catalog.ts"

BANNER = """// DO NOT EDIT — generated by scripts/gen_element_catalog.py.
//
// Astrid's element registry and renderers remain authoritative. This file is
// the deterministic, data-only projection imported by editor hosts such as
// Reigh; regenerate it when an element manifest or component changes.
"""


class _SkippedPackWarnings(logging.Handler):
    def __init__(self) -> None:
        super().__init__()
        self.messages: list[str] = []

    def emit(self, record: logging.LogRecord) -> None:
        message = record.getMessage()
        if message.startswith("skipping pack "):
            self.messages.append(message)


def generate() -> str:
    # Interactive registry discovery is fault tolerant. A checked-in catalog
    # must instead fail closed when an admitted pack has missing resources.
    _clear_registry_cache()
    warnings = _SkippedPackWarnings()
    logger = logging.getLogger("astrid.core.element.registry")
    logger.addHandler(warnings)
    try:
        descriptors = list_element_descriptors(include_shadowed=True)
    finally:
        logger.removeHandler(warnings)
    if warnings.messages:
        raise ValueError("Cannot generate an incomplete element catalog:\n" + "\n".join(warnings.messages))
    payload = json.dumps(descriptors, indent=2, sort_keys=True, ensure_ascii=False)
    return "\n".join(
        (
            BANNER.rstrip(),
            "",
            f"export const ASTRID_ELEMENT_CATALOG_VERSION = {EDITOR_CATALOG_VERSION} as const;",
            "",
            "export type AstridRenderingElementKind = 'effect' | 'animation' | 'transition';",
            "",
            "export type AstridRenderingElementParameter = {",
            "  name: string;",
            "  label: string;",
            "  description: string;",
            "  type: 'number' | 'select' | 'boolean' | 'color' | 'audio-binding';",
            "  default?: number | string | boolean;",
            "  min?: number;",
            "  max?: number;",
            "  step?: number;",
            "  options?: {label: string; value: string}[];",
            "};",
            "",
            "export type AstridRenderingElementDescriptor = {",
            "  id: string;",
            "  kind: AstridRenderingElementKind;",
            "  label: string;",
            "  description: string;",
            "  shortDescription: string;",
            "  keywords: string[];",
            "  defaults: Record<string, unknown>;",
            "  schema: Record<string, unknown>;",
            "  parameters: AstridRenderingElementParameter[];",
            "  source: string;",
            "  packId: string;",
            "  componentPath: string;",
            "  revision: string;",
            "  runtime: Record<string, unknown>;",
            "  renderability: {",
            "    preview: 'supported' | 'blocked' | 'unknown';",
            "    browserExport: 'supported' | 'blocked' | 'unknown';",
            "    workerExport: 'supported' | 'blocked' | 'unknown';",
            "  };",
            "};",
            "",
            "export const ASTRID_ELEMENT_CATALOG: readonly AstridRenderingElementDescriptor[] = Object.freeze(",
            payload,
            ");",
            "",
            "// Backwards-compatible name used by the editor integration.",
            "export const ASTRID_RENDERING_ELEMENTS = ASTRID_ELEMENT_CATALOG;",
            "",
            "export const ASTRID_EFFECT_CATALOG = ASTRID_ELEMENT_CATALOG.filter((element) => element.kind === 'effect');",
            "export const ASTRID_ANIMATION_CATALOG = ASTRID_ELEMENT_CATALOG.filter((element) => element.kind === 'animation');",
            "export const ASTRID_TRANSITION_CATALOG = ASTRID_ELEMENT_CATALOG.filter((element) => element.kind === 'transition');",
            "",
        )
    )


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("output", nargs="?", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when the checked-in projection differs from generated output",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    expected = generate()
    output = args.output.resolve()
    actual = output.read_text(encoding="utf-8") if output.is_file() else None
    if args.check:
        if actual != expected:
            print(f"{output} is stale; run scripts/gen_element_catalog.py", file=sys.stderr)
            return 1
        return 0
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
