#!/usr/bin/env python3
"""Generate the build-time browser extension projection for editor hosts."""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from astrid.core.pack import (  # noqa: E402
    PackValidationError,
    discover_packs,
    pack_editor_entry_paths,
)
from astrid.core.pack.canonical import (  # noqa: E402
    CanonicalPackValidationError,
    validate_canonical_pack,
)
from astrid.core.pack.definition import PackDefinition  # noqa: E402

DEFAULT_OUTPUT = REPO_ROOT / "astrid" / "packs" / "rendering" / "editor" / "catalog.ts"

BANNER = """// DO NOT EDIT — generated by scripts/gen_editor_extension_catalog.py.
//
// Pack manifests remain authoritative. This build-time projection imports only
// declared browser entries and is consumed by Reigh's trusted extension loader.
"""


def _editor_entries(pack: PackDefinition) -> tuple[Path, ...]:
    if pack.schema_version != "3":
        # The staged candidate still contains M13's captured v2 source. This
        # branch disappears with the separately owned corpus cutover.
        return pack_editor_entry_paths(pack)
    if not pack.ui:
        return ()
    try:
        canonical = validate_canonical_pack(pack.root, expected_pack_id=pack.id)
    except CanonicalPackValidationError as exc:
        raise PackValidationError(f"{pack.manifest_path}: editor projection: {exc}") from exc
    # These are the same declared handles used by F07's package closure. Do not
    # scan private siblings or infer required assets from TypeScript imports.
    resources = {handle.path: handle for handle in canonical.resource_handles}
    entries: list[Path] = []
    for key, contribution in canonical.definition.ui.items():
        # Whole-Tool declarations have a distinct launch projection. They do
        # not implement the ReighExtension contract consumed by this catalog.
        if contribution["type"] != "editor":
            continue
        location = f"{pack.manifest_path}: ui.{key}"
        if contribution.get("target", "video-editor") != "video-editor":
            raise PackValidationError(
                f"{location}.target: {contribution['target']!r} is unsupported; "
                "the current projection supports 'video-editor' or omission"
            )
        if "compatibility" in contribution and contribution["compatibility"] != {"sdk": "1"}:
            raise PackValidationError(
                f"{location}.compatibility: {contribution['compatibility']!r} is unsupported; "
                'the current video-editor projection supports omission or compatibility: {sdk: "1"} only'
            )
        handle = resources[contribution["entry"]]
        if handle.file_kind != "file" or handle.resolved.suffix not in {
            ".ts", ".tsx", ".js", ".jsx", ".mjs",
        }:
            raise PackValidationError(
                f"{location}.entry must name a browser JavaScript/TypeScript module: {handle.path}"
            )
        for resource in contribution.get("resources", ()):
            if resources[resource["path"]].file_kind != "file":
                raise PackValidationError(
                    f"{location}.resources must declare individual support/asset files: {resource['path']}"
                )
        entries.append(handle.resolved)
    return tuple(entries)


def _module_spec(pack_root: Path, entry: Path, output: Path, pack_id: str) -> str:
    module_path = entry.with_suffix("")
    if output.is_relative_to(pack_root):
        relative = Path(os.path.relpath(module_path, output.parent)).as_posix()
        return relative if relative.startswith(".") else f"./{relative}"
    return f"@astrid/packs/{pack_id}/{module_path.relative_to(pack_root).as_posix()}"


def generate(output: Path = DEFAULT_OUTPUT) -> str:
    rows: list[tuple[str, str, Path, str]] = []
    for pack in discover_packs():
        for entry in _editor_entries(pack):
            entry_path = entry.relative_to(pack.root).as_posix()
            rows.append(
                (
                    pack.id,
                    entry_path,
                    entry,
                    _module_spec(pack.root, entry, output.resolve(), pack.id),
                )
            )
    rows.sort(key=lambda row: (row[0], row[1]))

    imports = [
        f"import editorExtension{index} from {module_spec!r};"
        for index, (_, _, _, module_spec) in enumerate(rows)
    ]
    descriptors = [
        "  {"
        f" packId: {pack_id!r},"
        f" entryPath: {entry_path!r},"
        f" extension: editorExtension{index}"
        " }"
        for index, (pack_id, entry_path, _, _) in enumerate(rows)
    ]

    return "\n".join(
        (
            BANNER.rstrip(),
            "",
            "import type { ReighExtension } from '@reigh/editor-sdk';",
            *imports,
            "",
            "export type AstridEditorExtensionDescriptor = {",
            "  readonly packId: string;",
            "  readonly entryPath: string;",
            "  readonly extension: ReighExtension;",
            "};",
            "",
            "export const ASTRID_EDITOR_EXTENSION_CATALOG: readonly AstridEditorExtensionDescriptor[] = Object.freeze([",
            *[f"{descriptor}," for descriptor in descriptors],
            "]);",
            "",
            "export const ASTRID_EDITOR_EXTENSIONS: readonly ReighExtension[] = Object.freeze(",
            "  ASTRID_EDITOR_EXTENSION_CATALOG.map(({ extension }) => extension),",
            ");",
            "",
        )
    )


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("output", nargs="?", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when the checked-in projection differs from generated output",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    output = args.output.resolve()
    try:
        expected = generate(output)
    except (PackValidationError, OSError) as exc:
        print(f"editor catalog generation failed: {exc}", file=sys.stderr)
        return 1
    actual = output.read_text(encoding="utf-8") if output.is_file() else None
    if args.check:
        if actual != expected:
            print(f"{output} is stale; run scripts/gen_editor_extension_catalog.py", file=sys.stderr)
            return 1
        return 0
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
