from __future__ import annotations

import hashlib
import json
import subprocess
from pathlib import Path

import pytest

from astrid.core.execution.generic_host import GenericPackHost
from astrid.core.pack.discovery import discover_canonical_pack_metadata, discover_pack_metadata
from astrid.core.pack.source_setup import (
    DEFAULT_HIVEMIND_REPOSITORY,
    DEFAULT_HIVEMIND_REVISION,
    HIVEMIND_REPOSITORY_ENV,
    HIVEMIND_REVISION_ENV,
    SourceDeclaration,
    SourceSetupError,
    _tree_digest,
    active_source_inventory,
    default_source_declarations,
    hivemind_pin_report,
    provision,
)
from astrid.sdk.discovery import _discover_pack_inventory, _pack_record


def _git(root: Path, *args: str) -> str:
    return subprocess.check_output(["git", "-C", str(root), *args], text=True).strip()


def _fixture_repo(root: Path, *, schema_version: int = 2) -> str:
    root.mkdir()
    _git(root, "init", "-q", "-b", "main")
    _git(root, "config", "user.email", "fixture@example.test")
    _git(root, "config", "user.name", "Astrid fixture")
    pack = root
    executor = pack / "executors" / "echo"
    executor.mkdir(parents=True)
    (pack / "pack.yaml").write_text(
        f"schema_version: {schema_version}\nid: demo\nname: Demo Pack\nversion: 1.0.0\n"
        "capabilities: [testing]\n",
        encoding="utf-8",
    )
    (executor / "executor.yaml").write_text(
        json.dumps(
            {
                "id": "demo.echo",
                "name": "Demo Echo",
                "kind": "external",
                "version": "1.0",
                "command": {"argv": ["echo", "ok"]},
                "cache": {"mode": "none"},
            }
        ),
        encoding="utf-8",
    )
    _git(root, "add", ".")
    _git(root, "commit", "-q", "-m", "fixture")
    return _git(root, "rev-parse", "HEAD")


def _nested_fixture_repo(root: Path) -> tuple[Path, Path]:
    root.mkdir()
    _git(root, "init", "-q", "-b", "main")
    _git(root, "config", "user.email", "fixture@example.test")
    _git(root, "config", "user.name", "Astrid fixture")
    pack = root / "integrations" / "demo"
    pack.mkdir(parents=True)
    (pack / "pack.yaml").write_text(
        "schema_version: 2\nid: demo\nname: Demo\nversion: 1.0.0\ncapabilities: [testing]\n",
        encoding="utf-8",
    )
    actions = pack / "actions"
    actions.mkdir()
    (actions / "run.py").write_text("def run():\n    return 'first'\n", encoding="utf-8")
    outside = root / "README.md"
    outside.write_text("outside the selected pack\n", encoding="utf-8")
    _git(root, "add", ".")
    _git(root, "commit", "-q", "-m", "nested fixture")
    return root, pack


def _independent_digest(root: Path, names: tuple[str, ...]) -> str:
    digest = hashlib.sha256()
    for name in sorted(names):
        relative = name.encode()
        data = (root / name).read_bytes()
        digest.update(len(relative).to_bytes(8, "big"))
        digest.update(relative)
        digest.update(len(data).to_bytes(8, "big"))
        digest.update(data)
    return digest.hexdigest()


def test_nested_pack_digest_hashes_tracked_files_with_pack_relative_names(tmp_path: Path) -> None:
    _, pack = _nested_fixture_repo(tmp_path / "repository")

    expected = _independent_digest(pack, ("pack.yaml", "actions/run.py"))
    assert expected != hashlib.sha256(b"").hexdigest()
    assert _tree_digest(pack) == expected


def test_nested_pack_digest_changes_when_tracked_action_changes(tmp_path: Path) -> None:
    _, pack = _nested_fixture_repo(tmp_path / "repository")
    before = _tree_digest(pack)
    (pack / "actions" / "run.py").write_text("def run():\n    return 'changed'\n", encoding="utf-8")

    assert _tree_digest(pack) != before


def test_nested_pack_digest_excludes_outside_and_untracked_cache_files(tmp_path: Path) -> None:
    repository, pack = _nested_fixture_repo(tmp_path / "repository")
    before = _tree_digest(pack)
    (repository / "README.md").write_text("outside changed\n", encoding="utf-8")
    cache = pack / "__pycache__" / "generated.pyc"
    cache.parent.mkdir()
    cache.write_bytes(b"generated bytecode")
    (pack / "untracked.txt").write_text("untracked\n", encoding="utf-8")

    assert _tree_digest(pack) == before


def test_repository_root_pack_digest_preserves_tracked_tree_behavior(tmp_path: Path) -> None:
    repository = tmp_path / "repository"
    _fixture_repo(repository)

    expected = _independent_digest(repository, ("pack.yaml", "executors/echo/executor.yaml"))
    assert _tree_digest(repository) == expected


def test_default_source_policy_uses_full_delivery_hivemind_pin(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.delenv("ASTRID_SOURCE_DECLARATIONS", raising=False)
    monkeypatch.delenv(HIVEMIND_REVISION_ENV, raising=False)
    monkeypatch.delenv(HIVEMIND_REPOSITORY_ENV, raising=False)
    declarations = default_source_declarations()
    assert declarations[0].revision == DEFAULT_HIVEMIND_REVISION
    assert declarations[0].repository == DEFAULT_HIVEMIND_REPOSITORY
    assert hivemind_pin_report(declarations)["status"] == "configured"


def test_default_source_policy_accepts_only_a_configured_full_immutable_pin(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    revision = "a" * 40
    monkeypatch.setenv(HIVEMIND_REVISION_ENV, revision)
    declarations = default_source_declarations()
    assert declarations == (
        SourceDeclaration(
            pack_id="hivemind",
            repository=DEFAULT_HIVEMIND_REPOSITORY,
            revision=revision,
        ),
    )
    assert hivemind_pin_report(declarations)["status"] == "configured"

    monkeypatch.setenv(HIVEMIND_REVISION_ENV, "deadbeef")
    with pytest.raises(SourceSetupError, match="full immutable Hivemind Git object id"):
        default_source_declarations()


def test_local_git_v2_source_is_staged_once_and_shared(monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> None:
    repository = tmp_path / "repository"
    revision = _fixture_repo(repository)
    state_path = tmp_path / "state" / "pack-sources.json"
    data_root = tmp_path / "data"
    declaration = SourceDeclaration.from_mapping(
        {"pack_id": "demo", "repository": str(repository), "revision": revision}
    )
    monkeypatch.setenv("ASTRID_SOURCE_STATE", str(state_path))

    result = provision((declaration,), state_path=state_path, data_root=data_root)
    assert result["ok"] is True
    inventory = active_source_inventory(state_path=state_path)
    assert inventory.sources[0].pack_root.is_dir()
    assert inventory.sources[0].revision == revision

    discovered = discover_pack_metadata(discover_packs_fn=lambda *args: ())
    managed = next(item for item in discovered if item.id == "demo")
    assert managed.source_kind == "managed"
    assert managed.source_inventory_identity == inventory.identity
    assert managed.source_revision == revision
    canonical = next(item for item in discover_canonical_pack_metadata() if item.id == "demo")
    assert canonical.source_kind == "managed"
    assert canonical.source_inventory_identity == inventory.identity
    sdk_record = _pack_record(next(item for item in _discover_pack_inventory() if item.id == "demo"))
    assert sdk_record["source_kind"] == "managed"
    assert sdk_record["source_inventory_identity"] == inventory.identity

    host = GenericPackHost(
        pack_roots=[*map(str, inventory.roots)],
        source_inventory_identity=inventory.identity,
    )
    record = next(item for item in host.discover() if item.id == "demo.echo")
    assert Path(record.definition.metadata["pack_root"]) == inventory.sources[0].pack_root
    assert host.source_inventory_identity == inventory.identity
    assert host.source_epoch != "uninitialized"

    before = state_path.read_bytes()
    checked = provision((declaration,), check=True, state_path=state_path, data_root=data_root)
    assert checked["changed"] is False
    assert state_path.read_bytes() == before

    offline = provision((declaration,), offline=True, state_path=state_path, data_root=data_root)
    assert offline["ok"] is True
    disabled = provision((), disable_pack="demo", state_path=state_path, data_root=data_root)
    assert disabled["active"] == []
    assert active_source_inventory(state_path=state_path).sources == ()
    restored = provision(
        (declaration,), offline=True, restore_pack="demo", state_path=state_path, data_root=data_root
    )
    assert restored["ok"] is True
    assert active_source_inventory(state_path=state_path).sources[0].revision == revision


def test_managed_source_requires_canonical_v2_v3_manifest(tmp_path: Path) -> None:
    repository = tmp_path / "repository"
    revision = _fixture_repo(repository, schema_version=1)
    state_path = tmp_path / "state" / "pack-sources.json"
    data_root = tmp_path / "data"
    declaration = SourceDeclaration.from_mapping(
        {"pack_id": "demo", "repository": str(repository), "revision": revision}
    )

    with pytest.raises(SourceSetupError, match="canonical v2/v3 admission"):
        provision((declaration,), state_path=state_path, data_root=data_root)
    assert not state_path.exists()


def test_invalid_update_keeps_prior_active_state(tmp_path: Path) -> None:
    repository = tmp_path / "repository"
    revision = _fixture_repo(repository)
    state_path = tmp_path / "state" / "pack-sources.json"
    data_root = tmp_path / "data"
    first = SourceDeclaration.from_mapping(
        {"pack_id": "demo", "repository": str(repository), "revision": revision}
    )
    provision((first,), state_path=state_path, data_root=data_root)
    prior_state = state_path.read_bytes()

    (repository / "pack.yaml").write_text(
        "schema_version: 1\nid: demo\nname: Broken\nversion: 1.0.0\n", encoding="utf-8"
    )
    _git(repository, "add", "pack.yaml")
    _git(repository, "commit", "-q", "-m", "invalid-update")
    bad_revision = _git(repository, "rev-parse", "HEAD")
    bad = SourceDeclaration.from_mapping(
        {"pack_id": "demo", "repository": str(repository), "revision": bad_revision}
    )

    with pytest.raises(SourceSetupError, match="canonical v2/v3 admission"):
        provision((bad,), state_path=state_path, data_root=data_root)
    assert state_path.read_bytes() == prior_state
    assert active_source_inventory(state_path=state_path).sources[0].revision == revision


def test_active_checkout_tamper_fails_closed(tmp_path: Path) -> None:
    repository = tmp_path / "repository"
    revision = _fixture_repo(repository)
    state_path = tmp_path / "state" / "pack-sources.json"
    data_root = tmp_path / "data"
    declaration = SourceDeclaration.from_mapping(
        {"pack_id": "demo", "repository": str(repository), "revision": revision}
    )
    provision((declaration,), state_path=state_path, data_root=data_root)
    active_root = active_source_inventory(state_path=state_path).sources[0].pack_root
    # Interpreter caches are ignored generated files and must not invalidate
    # the immutable tracked-tree digest of an installed source.
    (active_root / ".git" / "info" / "exclude").write_text("__pycache__/\n*.pyc\n", encoding="utf-8")
    cache = active_root / "__pycache__" / "generated.pyc"
    cache.parent.mkdir()
    cache.write_bytes(b"generated bytecode")
    assert active_source_inventory(state_path=state_path).sources[0].revision == revision
    (active_root / "pack.yaml").write_text(
        (active_root / "pack.yaml").read_text(encoding="utf-8") + "\n# tampered\n",
        encoding="utf-8",
    )
    with pytest.raises(SourceSetupError, match="dirty|digest mismatch"):
        active_source_inventory(state_path=state_path)


def test_failed_stage_removes_temporary_checkout_and_keeps_state_absent(tmp_path: Path) -> None:
    repository = tmp_path / "repository"
    _fixture_repo(repository)
    state_path = tmp_path / "state" / "pack-sources.json"
    data_root = tmp_path / "data"
    declaration = SourceDeclaration.from_mapping(
        {
            "pack_id": "demo",
            "repository": str(repository),
            "revision": "0" * 40,
        }
    )
    with pytest.raises(SourceSetupError):
        provision((declaration,), state_path=state_path, data_root=data_root)
    if (data_root / "demo").exists():
        assert not list((data_root / "demo").glob("stage-*"))
    assert not state_path.exists()


def test_offline_missing_cache_and_tamper_fail_closed(tmp_path: Path) -> None:
    repository = tmp_path / "repository"
    revision = _fixture_repo(repository)
    state_path = tmp_path / "state" / "pack-sources.json"
    data_root = tmp_path / "data"
    declaration = SourceDeclaration.from_mapping(
        {"pack_id": "demo", "repository": str(repository), "revision": revision}
    )

    missing = provision(
        (declaration,), offline=True, check=True, state_path=state_path, data_root=data_root
    )
    assert missing["ok"] is False
    assert "cached revision is missing" in missing["errors"][0]

    provision((declaration,), state_path=state_path, data_root=data_root)
    active = active_source_inventory(state_path=state_path)
    (active.sources[0].pack_root / "pack.yaml").write_text(
        (active.sources[0].pack_root / "pack.yaml").read_text(encoding="utf-8")
        + "\n# tampered\n",
        encoding="utf-8",
    )
    with pytest.raises(SourceSetupError, match="dirty"):
        active_source_inventory(state_path=state_path)
