"""Shared Astrid schema contracts used across executors and orchestrators."""

from .artifact_types import (
    ARTIFACT_TYPE_REGISTRY,
    ArtifactTypeDescriptor,
    ArtifactTypeRegistry,
    ArtifactTypeRegistryError,
)
from .errors import (
    AstridError,
    AstridErrorEnvelope,
    build_state_snapshot,
    coerce_astrid_error,
    error_from_result,
    normalize_valid_options,
    render_astrid_error,
    wrap_degraded_error,
)
from .identifiers import (
    IdentifierValidationError,
    generate_group_id,
    generate_run_id,
    is_ulid,
    require_ulid,
    validate_timeline_slug,
    validate_timeline_ulid,
)
from .project_theme import (
    ProjectStyleSnapshot,
    ProjectThemeBinding,
    validate_project_identifier,
    validate_theme_identifier,
)
from .schema import (
    CACHE_MODES,
    ISOLATION_MODES,
    OUTPUT_MODES,
    PORT_REQUIRED_TYPES,
    AliasRecord,
    CachePolicy,
    CapabilityHandle,
    CommandSpec,
    IsolationMetadata,
    Output,
    Port,
    Provenance,
    SafetyDeclaration,
)
from .scoped_config import (
    SCOPE_REGISTRY,
    ScopedConfig,
    ScopeKey,
    ScopeRegistry,
    ScopeRequest,
)
from .writer import (
    TransactionControlError,
    WriterBusyError,
    WriterError,
    WriterShutdownError,
    WriterSidecarError,
)

__all__ = [
    "ARTIFACT_TYPE_REGISTRY",
    "ArtifactTypeDescriptor",
    "ArtifactTypeRegistry",
    "ArtifactTypeRegistryError",
    "CACHE_MODES",
    "ISOLATION_MODES",
    "OUTPUT_MODES",
    "PORT_REQUIRED_TYPES",
    "AstridError",
    "AstridErrorEnvelope",
    "AliasRecord",
    "build_state_snapshot",
    "CachePolicy",
    "CapabilityHandle",
    "CommandSpec",
    "coerce_astrid_error",
    "error_from_result",
    "IsolationMetadata",
    "normalize_valid_options",
    "Output",
    "Port",
    "Provenance",
    "render_astrid_error",
    "SCOPE_REGISTRY",
    "SafetyDeclaration",
    "ScopeKey",
    "ScopeRegistry",
    "ScopeRequest",
    "ScopedConfig",
    "IdentifierValidationError",
    "generate_group_id",
    "generate_run_id",
    "is_ulid",
    "require_ulid",
    "ProjectStyleSnapshot",
    "ProjectThemeBinding",
    "validate_project_identifier",
    "validate_theme_identifier",
    "validate_timeline_slug",
    "validate_timeline_ulid",
    "wrap_degraded_error",
    "TransactionControlError",
    "WriterBusyError",
    "WriterError",
    "WriterShutdownError",
    "WriterSidecarError",
]
